# Generated by Django 2.2.5 on 2019-10-12 08:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceq',
            name='question_image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None),
        ),
        migrations.AlterField(
            model_name='fillblankq',
            name='question_content',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20000), size=None),
        ),
        migrations.AlterField(
            model_name='fillblankq',
            name='question_image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None),
        ),
        migrations.AlterField(
            model_name='trueorfalseq',
            name='question_image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None),
        ),
    ]
