# Generated by Django 2.2.5 on 2019-10-18 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpermissions',
            old_name='edit_admins',
            new_name='change_user_group',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='edit_students',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='promote_students',
        ),
    ]
