# Generated by Django 2.2.5 on 2019-10-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_banned',
        ),
        migrations.AddField(
            model_name='student',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
