# Generated by Django 2.2.5 on 2019-10-22 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('backend', '0002_auto_20191018_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('picture', models.CharField(max_length=10000000)),
                ('brief', models.CharField(max_length=20000)),
                ('createTime', models.DateTimeField()),
                ('lastUpdate', models.DateTimeField()),
                ('authority', models.CharField(max_length=200)),
                ('question_count', models.IntegerField()),
                ('invitation_code_count', models.IntegerField()),
                ('activated_code_count', models.IntegerField()),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_backend.questionbank_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.RemoveField(
            model_name='knowledgenode',
            name='node_id',
        ),
        migrations.AlterField(
            model_name='knowledgenode',
            name='question_bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.QuestionBank'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='belong_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.QuestionBank'),
        ),
        migrations.DeleteModel(
            name='QuestionBanks',
        ),
    ]
