# Generated by Django 2.2.5 on 2019-11-21 12:14

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20191119_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='change_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 21, 12, 14, 38, 953237, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 21, 12, 14, 53, 781669, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='point_every_blank',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[1], size=None),
            preserve_default=False,
        ),
    ]
