# Generated by Django 2.2.5 on 2019-10-23 14:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20191022_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefanswerq',
            name='question_image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=200), size=None),
        ),
        migrations.AlterField(
            model_name='choiceq',
            name='question_image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
        migrations.AlterField(
            model_name='fillblankq',
            name='question_image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
        migrations.AlterField(
            model_name='knowledgenode',
            name='name',
            field=models.CharField(default='unnamed node', max_length=200),
        ),
        migrations.AlterField(
            model_name='trueorfalseq',
            name='question_image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
    ]
