# Generated by Django 2.2.5 on 2019-11-21 12:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20191121_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='point_every_blank',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
