# Generated by Django 2.2.5 on 2019-10-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20191022_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationrecord',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
