# Generated by Django 2.2.5 on 2019-10-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_emailverificationrecord_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationrecord',
            name='token',
            field=models.CharField(max_length=50, verbose_name='Code'),
        ),
    ]
