# Generated by Django 2.2.5 on 2019-10-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20191022_0358'),
        ('backend', '0005_auto_20191024_1507'),
    ]

    operations = [
    ]
