# Generated by Django 2.2.5 on 2019-10-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_merge_20191024_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationrecord',
            name='send_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Send time'),
        ),
        migrations.AlterField(
            model_name='emailverificationrecord',
            name='send_type',
            field=models.CharField(choices=[('register', 'Register'), ('forget', 'Reset password')], max_length=10, verbose_name='Veification type'),
        ),
    ]
