# Generated by Django 2.2.5 on 2019-10-31 14:14

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('backend', '0009_auto_20191026_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='questionversion',
            name='paper',
        ),
        migrations.AddField(
            model_name='paper',
            name='status',
            field=models.CharField(default='drafted', max_length=200),
        ),
        migrations.AddField(
            model_name='paper',
            name='tips',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
        migrations.AddField(
            model_name='paper',
            name='title',
            field=models.CharField(default='unmaned paper', max_length=200),
        ),
        migrations.AddField(
            model_name='paper',
            name='total_point',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='questionversion',
            name='question_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paper',
            name='name',
            field=models.CharField(default='unmaned paper', max_length=200),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('total_point', models.IntegerField()),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_backend.section_set+', to='contenttypes.ContentType')),
                ('questions', models.ManyToManyField(through='backend.QuestionVersion', to='backend.QuestionGroup')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='questionversion',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.Section'),
        ),
    ]
