# Generated by Django 2.2.5 on 2019-11-01 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20191031_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionversion',
            name='question_version',
        ),
        migrations.AlterField(
            model_name='questionversion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Question'),
        ),
        migrations.AlterField(
            model_name='section',
            name='questions',
            field=models.ManyToManyField(through='backend.QuestionVersion', to='backend.Question'),
        ),
    ]
