# Generated by Django 2.2.5 on 2019-11-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20191101_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_latest',
            field=models.BooleanField(default=True),
        ),
    ]
