# Generated by Django 2.2.5 on 2019-11-03 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_section_is_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='belong_paper',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.Paper'),
            preserve_default=False,
        ),
    ]
