# Generated by Django 2.2.5 on 2019-11-03 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20191103_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionversion',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Section'),
        ),
    ]
