# Generated by Django 2.2.5 on 2019-11-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20191103_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='is_latest',
        ),
        migrations.AddField(
            model_name='paper',
            name='is_latest',
            field=models.BooleanField(default=True),
        ),
    ]
