# Generated by Django 2.2.5 on 2019-11-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20191103_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionversion',
            name='question_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='section_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
