# Generated by Django 2.2.5 on 2019-11-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20191104_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='tips',
            field=models.CharField(default='', max_length=200),
        ),
    ]
