# Generated by Django 2.2.5 on 2019-11-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20191105_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='name',
        ),
        migrations.RemoveField(
            model_name='section',
            name='name',
        ),
        migrations.AddField(
            model_name='paper',
            name='time_limit',
            field=models.IntegerField(default=0),
        ),
    ]
