# Generated by Django 2.2.5 on 2019-11-09 13:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20191105_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='have_brief_ans',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionversion',
            name='point_every_blank',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
