# Generated by Django 2.2.5 on 2019-11-12 04:16

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20191109_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField(auto_now=True)),
                ('is_timed', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('time_left', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('user_total_points', models.IntegerField(default=0)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Paper')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('question_type', models.CharField(default='', max_length=20)),
                ('record_time', models.DateTimeField(auto_now=True)),
                ('ans', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=20000), size=None)),
                ('score', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('is_correct', models.BooleanField(blank=True)),
                ('paper_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.PaperRecord')),
            ],
        ),
    ]
