# Generated by Django 2.2.5 on 2019-11-13 08:57

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20191113_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='question_banks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[-1], size=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, unique=True)),
                ('time_generated', models.DateTimeField(auto_now=True)),
                ('is_usable', models.BooleanField(default=True)),
                ('question_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.QuestionBank')),
            ],
        ),
    ]
