# Generated by Django 2.2.5 on 2019-11-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20191113_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
